### ISSUE TITLE
Glibc stage3 tarball is now compressed in tar.xz

### ISSUE THREAD

**Issue by babykart** [edannenberg/kubler#138] opened 2018-01-14 12:50 UTC
Since january 4th, the glibc stage3 archive is compressed in tar.xz.
As a result, kubler fails to update and to create the kubler-gentoo/stage3-amd64-hardened-nomultilib image.

**Comment by edannenberg** [comment] 2018-01-15 08:45
Thanks for reporting, fix is up.

On an unrelated note emerge on musl seems to hang now due to `misc-functions.sh` crashing during the install phase. (ps aux shows: `portage [misc-functions.] <defunct>`) Glibc is working fine, not sure if it's a musl upstream regression or a local problem on my end. If you happen to rebuild some feedback would be appreciated.

**Comment by babykart** [comment] 2018-01-15 17:36
The fix works fine, thank you.
For the musl builder, I have the same problem: misc-functions.sh crashed.
Probably a regression on musl upstream.

**Comment by edannenberg** [comment] 2018-01-15 20:37
Thanks for confirming, also fixed now, that was a fun one. >< See #139 for details.

**Closed by edannenberg** 2018-01-15 20:37 UTC
Labels: enhancement
