### ISSUE TITLE
Problems with /usr/lib64/misc/ssh-keysign

### ISSUE THREAD

**Issue by paneidos** [edannenberg/kubler#121] opened 2017-04-05 22:06 UTC
On a fresh checkout I got an error concerning "suid/sgid file(s) with suspicious hardlink(s)", listing /usr/lib64/misc/ssh-keysign as the culprit.
I encountered this error before while experimenting when it this project was called 'gentoobb'.

<details>

```
--> build image kubler/openssl
--> phase 1: building root fs
using kubler/bob-s6:20170326
 * This action can remove important packages! In order to be safer, use
 * `emerge -pv --depclean <atom>` to check for reverse dependencies before
 * removing packages.


!!! 'net-misc/openssh' (virtual/ssh) is part of your system profile.
!!! Unmerging it may be damaging to your system.


 net-misc/openssh
    selected: 7.3_p1-r7
   protected: none
     omitted: none

All selected packages: =net-misc/openssh-7.3_p1-r7

>>> 'Selected' packages are slated for removal.
>>> 'Protected' and 'omitted' packages will not be removed.

>>> Waiting 5 seconds before starting...
>>> (Control-C to abort)...
>>> Unmerging in: 5 4 3 2 1
>>> Unmerging (1 of 1) net-misc/openssh-7.3_p1-r7...
 * suid/sgid file(s) with suspicious hardlink(s):
 *
 *      /usr/lib64/misc/ssh-keysign
 *
 * See the Gentoo Security Handbook guide for advice on how to proceed.
fatal: Failed to run image kubler/bob-s6:20170326
--> remove kubler-openssl-3664-11732, NO_CLEANUP env prevents this
```

</details>

One solution that has worked on another machine is adding
`rm /usr/lib64/misc/ssh-keysign`
to `configure_bob()` of the openssl image.

**Comment by edannenberg** [comment] 2017-04-06 12:33
Thanks for the report, I have definitely seen this before, though it never failed the build so far, so I treated it as a warning. To make things even more odd I just tested this with a fresh clone and don't get the warning/error at all:

```bash
$ kubler build -i kubler/openssl
$ ls -lah /usr/lib64/misc/ssh-keysign
-rws--x--x 1 root root 436K Mar 17 06:24 /usr/lib64/misc/ssh-keysign
```

```
$ kubler build -n -F kubler/openssl
--> build image kubler/openssl
Untagged: kubler/openssl:20170326
--> phase 1: building root fs
using kubler/bob-s6:20170326
 * This action can remove important packages! In order to be safer, use
 * `emerge -pv --depclean <atom>` to check for reverse dependencies before
 * removing packages.


!!! 'net-misc/openssh' (virtual/ssh) is part of your system profile.
!!! Unmerging it may be damaging to your system.


 net-misc/openssh
    selected: 7.3_p1-r7
   protected: none
     omitted: none

All selected packages: =net-misc/openssh-7.3_p1-r7

>>> 'Selected' packages are slated for removal.
>>> 'Protected' and 'omitted' packages will not be removed.

>>> Waiting 5 seconds before starting...
>>> (Control-C to abort)...
>>> Unmerging in: 5 4 3 2 1
>>> Unmerging (1 of 1) net-misc/openssh-7.3_p1-r7...

 * IMPORTANT: 10 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

Calculating dependencies... done!

>>> Emerging binary (1 of 1) dev-libs/openssl-1.0.2k::gentoo
...
```

The log above is from a rebuild, the initial build didn't display the message either.

Can you please post your docker version and your build host OS?

```
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Thu Mar 30 15:34:50 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Thu Mar 30 15:34:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by soredake** [comment] 2017-04-06 12:41
I got this too (https://github.com/edannenberg/kubler/issues/38#issue-183839419), mine docker/os is
```
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Fri Mar 31 02:09:07 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Fri Mar 31 02:09:07 2017
 OS/Arch:      linux/amd64
```

```
$ cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.7.0
VERSION_ID=1298.7.0
BUILD_ID=2017-03-31-0215
PRETTY_NAME="Container Linux by CoreOS 1298.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
https://github.com/edannenberg/kubler/issues/38#issue-183839419

**Comment by edannenberg** [comment] 2017-04-06 13:57
Ah, I 'member now. :) Well lets see if we get a match, might be some hardening option of coreOS that triggers this. I'll add the fix for this either way.

**Comment by paneidos** [comment] 2017-04-06 14:28
```
$ docker version                                                                                                                                                                                                                    1 ↵
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.4
 Git commit:   78d1802
 Built:        Wed Feb 15 11:34:46 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.4
 Git commit:   78d1802
 Built:        Wed Feb 15 11:34:46 2017
 OS/Arch:      linux/amd64
```

```
$ cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
```

Kernel: gentoo-sources

**Comment by edannenberg** [comment] 2017-04-06 15:44
Hmm that would suggest the Docker version, though I'm fairly sure I ran this version too at some point. Maybe the storage backend? Pretty much out of ideas otherwise.

```
$ docker info | grep Storage
Storage Driver: devicemapper
```

**Comment by paneidos** [comment] 2017-04-06 18:05
I've had the problem with overlay and overlay2. Both running Gentoo.

**Comment by edannenberg** [comment] 2017-04-07 14:02
Coincidentally I installed a new docker box yesterday. Host: Gentoo, Docker 1.12.6 and overlay2 storage. Pretty much as vanilla as it gets. Build ran fine without the fix. @paneidos, any extra hardening like apparmor/selinux active on your box?

**Comment by paneidos** [comment] 2017-04-07 16:13
No, nothing special.

**Comment by edannenberg** [comment] 2017-04-07 16:36
Looks like one for the mystery box then. Closing this as the fix addresses the issue, would have been nice to know the cause though. Let us know if you run into any other odd behaviour.

**Closed by edannenberg** 2017-04-07 16:36 UTC

**Comment by paneidos** [comment] 2017-04-19 07:48
I've done some more research and experimenting.
The issue does not occur with overlay2, but only with the overlay storage drvier. It occurs because the overlay storage driver uses hardlinks to reduce the number of layers, as the first version of overlayfs only supported two layers. Therefore Portage detects 'suspicious' hardlinks when removing this file. Overlay2 does support multiple layers, which means Docker does not make use of hardlinks to reduce the number of layers.

**Comment by edannenberg** [comment] 2017-04-19 14:21
Ah, thanks for letting us know, I'll add a note to the [workaround](https://github.com/edannenberg/kubler/blob/master/dock/kubler/images/openssl/build.sh#L8).
