### ISSUE TITLE
Missing documentation, and the future of project

### ISSUE THREAD

**Issue by UralZima** [edannenberg/kubler#43] opened 2016-12-03 10:48 UTC
Hello. I think this project is a big future of Docker mess.
Man, this is the most acceptable way to use Docker, but there are little problems:

1. Nobody knows about it. I can't find any info at google, only a few blog posts and nothing more. I am sure, that people new to Gentoo, but familiar with Docker will like this way of managing containers. Anyone who have a blog, please tell about this great project! Many people use Gentoo for host and default crappy dockerhub's ubuntu images. 
2. No any documentation. I needed much time to understand and to be sure use it in production (being advanced gentoo user), coz for such big thing one little readme.md is nothing.  The first problem also links here. 

After resolving 2nd issue, I will post an article on russian's biggest it-blog - geektimes.ru, it means many contributors, users and much attention. 

So as I created an issue, let the topic will be documentation. I prepared some questions after monthly use of your project. It may be a starting point for some detailed doc. 

The questions may be annonying or a kind of stupid, but I don't have time to learn all bash scripts and imagine how they works. I found your project while preparing a big production. I think many people will have same questions after using your project.

1. Some of packages use gentoobb/bash as source container, some packages use 'provide_package bash' and sources s6/openssl in their config. What is the difference? Please tell more about provide_package. As I understood, it add all package's file, if it is installed in upstream parent container(s). What I need to use, if I want to see bash in all containers? Just use FROM bash, instead of FROM s6?
2. Tell us more about bob-interactive. Sometimes I tried to use it to emerge manually, but after it starts following Buildconfig.sh and rebuilds again. Maybe some more examples?
2. I failed to build bind-9.11.0 with configure: error: cannot compute suffix of object files: cannot compile. 
It was successfully built with bob-interactive, and then rebuilt again with buildroot. Autogen and binutils was added in provide_package
3. After creating some custom packages, there was some missing libraries. Examples: latest mariadb (~amd64) was missing liblzma.5.so, after adding it worked. bind dns server is missing libdb-4.8.so, but host don't have it, it is still unresolved for me now. How to avoid it? Maybe call ldd on executables automatically and copy all missing libs? It must be easy to add such functionality.
4. Why I can't see running service in top and ps inside container? Is it possible somehow?
5. How to restart s6 service, instead of restarting the whole container?
6. Is it possible to add a package to existing container without rebuilding?
7. (a bit offtopic) Is there any reason to use more updated toolchain and main utils (like newer glibc, gcc, etc). Gcc is already at 6.0 version, but gentoo considers stable only 4.9.3... same with many other apps.
8. You said s6 is optional. How to use default openrc and not spent time to create s6/run and other things? It is  hard to average user to do so (ex. for bind, which runs in chroot by default)
9. I use bob as default builder. Busybox is built with bob-musl. And my images contains a mix? How it works? 
10. Please describe more functions configure_bob, configure_rootfs_build and finish_rootfs_build. Please use more examples in your future doc. 
11. Why sometimes curl and some packages are providing, unproviding, etc? Can you tell us more, to avoid mistakes of creating new packages. 
12. I found your project when was preparing a high-load production server. I created 7-10 containers, containing different services. How rebuilding everything works? As I understood, if I have some containers (not images) depending on some image, it will be not deleted, and I am not sure it will update. Tags? Who will have :latest? Also, I was forced to add emerge --sync to some images, coz I needed latest version of package, but had month-old stage3. Is there any way to call emerge --sync at least once a day for some parent container? I am afraid to call update/rebuild to anything, coz I am not fully understand how it works. Please describe some steps/examples, how to update anything in production environment, and keep emerge synced for all new images.
13. Why you call 'emerge php' in configure_bob, but in all other packages emerge is called from build script? what's the difference?
14. When I need to use 'copy_gcc_libs' on new images? Why some work, some not?

Man, you made a great cool thing, you can't imagine how big is future of this project. I see it in such way: 
Big documentation, many examples, many repos of prepared packages for gentoobb, many blog posts/success stories, and mentioning on Gentoo.org Docker's wiki pages, also adding it to portage or some overlays. 

Please pay some attention to the 'cover' of project, coz the kernel and all inside is just fine. We need some more attention and pull requests from other people. 

I will help as I can, but have a hard-time of preparing production servers. 

Thank you very much!
Good luck!

**Comment by edannenberg** [comment] 2016-12-06 01:40
Thanks for the kind words. Yeah, the documentation is far from complete and a question catalog like this is very helpful. 

> 1. Some of packages use gentoobb/bash as source container, some packages use 'provide_package bash' and sources s6/openssl in their config. What is the difference? Please tell more about provide_package. As I understood, it add all package's file, if it is installed in upstream parent container(s). What I need to use, if I want to see bash in all containers? Just use FROM bash, instead of FROM s6?

[provide_package](https://github.com/edannenberg/gentoo-bb/blob/2f1e59c029a05665336ea1d5fbff7e27879606e4/bob-core/build-root.sh#L213) is just a little helper function that adds the given package atom to Portage's `package.provided` file. Imagine you want to install package Y which has `bash` in it's dependency graph. If you don't want bash you would use this helper to effectively skip the package.

> 3. I failed to build bind-9.11.0 with configure: error: cannot compute suffix of object files: cannot compile.
It was successfully built with bob-interactive, and then rebuilt again with buildroot. Autogen and binutils was added in provide_package

Probably related to misunderstanding of `provide_package`. If the issue persists you can open a seperate ticket with more details.

> 5. Why I can't see running service in top and ps inside container? Is it possible somehow?

This should work as expected, also there is `docker top <container_id> <ps_options>`

> 6. How to restart s6 service, instead of restarting the whole container?

See http://skarnet.org/software/s6/s6-svc.html You can also send the usual signals like `HUP` via `kill`, i.e. `docker exec -it <container_id> kill -1 <pid>`.

> 7. Is it possible to add a package to existing container without rebuilding?

No, which is by design. See my answer to 13. for more.

> 8. (a bit offtopic) Is there any reason to use more updated toolchain and main utils (like newer glibc, gcc, etc). Gcc is already at 6.0 version, but gentoo considers stable only 4.9.3... same with many other apps.

Only to keep things easier to maintain. You can configure the build container via `configure_bob` hook as you wish. Example for "unstable" gcc:

     configure_bob() {
           update_keywords sys-devel/gcc `+~amd64`
           emerge gcc
          <switch gcc via gcc-config>
     }

> 9. You said s6 is optional. How to use default openrc and not spent time to create s6/run and other things? It is hard to average user to do so (ex. for bind, which runs in chroot by default)

The reason against openrc is mainly it's footprint as it requires a full python installation. s6 is orders of magnitude smaller. It's usually not that hard to port a openrc init file to s6 though. You could also skip s6 or any other init system and simply start the process or provide a small shell script for some initial house keeping. I'll try to add some pointers on how to go about the openrc->s6 process in general to the docs. That being said you are free to create a openrc image and use that instead of s6 as a base for your other images.

> 10. I use bob as default builder. Busybox is built with bob-musl. And my images contains a mix? How it works?

Good question, a bit tricky to get with the current documention.  What happens is that `bob-musl` is used to create the `gentoo-bb/busybox` image. Then `gentoobb/glibc`, which uses `FROM gentoobb/busybox`, is built, but instead of using the parent `bob-musl-busybox` build container we [switch](https://github.com/edannenberg/gentoo-bb/blob/master/dock/gentoobb/images/glibc/Dockerfile.template#L4) to the default `bob` build container. A bit obscure, and rarely needed.

> 12. Why sometimes curl and some packages are providing, unproviding, etc? Can you tell us more, to avoid mistakes of creating new packages.

Some packages require header and/or library files of packages that already got installed in a parent image. As all parent packages are in the `package.provided` file of the build container the required files can't be found during build time. By unproviding the package, Portage will pull it in again, the build completes and usually you uninstall the package again in the `finish_rootfs` hook.

> 13. I found your project when was preparing a high-load production server. I created 7-10 containers, containing different services. How rebuilding everything works? As I understood, if I have some containers (not images) depending on some image, it will be not deleted, and I am not sure it will update. Tags? Who will have :latest? Also, I was forced to add emerge --sync to some images, coz I needed latest version of package, but had month-old stage3. Is there any way to call emerge --sync at least once a day for some parent container? I am afraid to call update/rebuild to anything, coz I am not fully understand how it works. Please describe some steps/examples, how to update anything in production environment, and keep emerge synced for all new images.

There are 2 philosophies when it comes to running containers, the old and first (OpenVZ, etc) is to treat a container like a lightweight VM. The container is basically never deleted and updates are applied in a running container. Docker brought a new philosophy to the table, which treats containers as disposable processes. They are deleted frequently and updates are applied by downloading a newer version of the image and re-creating the container from scratch. gentoo-bb tries to fully embrace this philosophy. There is no portage tree or tool chain in the final images. All runtime data (database, etc) should be kept in docker data volumes or mounted from host so you can dispose of containers at any time. 

A rough outline of how I do the monthly rebuilds on our build server:

* run `./build.sh update` to fetch and set current stage3 date from gentoo server
* delete all images on build server, run `find . -name rootfs.tar -exec rm {} \;` to delete all rootfs.tar files in repo, not required but makes things a bit easier when trying to continue after errors
* run `./build.sh` to start build
* push new images to internal image repo
* deploy new images to servers / recreate containers, this is out of scope for this project and depends on your infrastructure, you should find plenty of information/solutions for this

> 14. Why you call 'emerge php' in configure_bob, but in all other packages emerge is called from build script? what's the difference?

This is a trick to work around build failures for some packages. See #33 for details.

> 15. When I need to use 'copy_gcc_libs' on new images? Why some work, some not?

Some packages require `libstdc++`, for now you will have to test the image to see if it is needed or not. Maybe some sort of ldd check as you suggested earlier is feasible.

---

I'll try to expand a bit more in the coming days and use this issue as a base for extending the documentation. Probably time for a wiki or gh-pages. Feel free to keep poking for more details!

**Comment by azimut** [comment] 2016-12-07 16:15
a dot/graphviz graph build from the .sh/templates of the current images is something that could be scripted too

**Comment by azimut** [comment] 2016-12-10 20:44
Another way to help with the docs could be:
* Expose more stages of the build process as different actions. Such as ebuild does it https://devmanual.gentoo.org/ebuild-writing/functions/ for example by adding actions to just build the core or just download stage3.
* Also on the same line of though it would help if the actions or commands rely less on defaults and have mandatory arguments. And in the case of missing the correct help would appear listing what is missing and how can you provide it (for instance an namespace or a image on the namespace)

**Comment by edannenberg** [comment] 2017-01-03 23:02
@azimut I like the graphviz idea, will most likely be integrated when I do the coming acbuild switch. Thanks for the gist.

> Expose more stages of the build process as different actions. Such as ebuild does it https://devmanual.gentoo.org/ebuild-writing/functions/ for example by adding actions to just build the core or just download stage3.

I tried to keep `build.sh` as generic as possible, so I'm not sold on adding something like `buildbusyboxbuild`, it's to specific and `build gentoobb/busybox` is not that much longer while being more precise as it tells you exactly what image you are building. Maybe some sort of generic mechanism to expose extra commands/options via `build.sh` per build "engine" (i.e. `docker.sh`) is feasable.

The `-Fn` or `-fn` options usually do the trick for me while tinkering, but `-c` should rebuild all build containers for the current dep graph while `-C` will rebuild the whole stack starting with stage3 import. I say should because it has been quite a while since I used those, might not have survived the last big refactor. :p

> Also on the same line of though it would help if the actions or commands rely less on defaults and have mandatory arguments.

I'm a big fan of convention over configuration, but there is def. room for improvement. I'll give this some more thought, also curious what other people think on this.

> Some references or links to "docker commit" https://docs.docker.com/engine/reference/commandline/commit/ and emerge "--root" https://dev.gentoo.org/~zmedico/portage/doc/man/emerge.1.html#lbAH option used would help to clarify the design.

Noted, it will probably also be necessary to provide a Portage 101 for people not familiar with gentoo.

---

Might as well put this here, after the much needed holidays I'll probably start the acbuild refactor and doc rewrite this month. As I'm not that happy with the project name for a while now I have been thinking about renaming the project to `cbob`, for container bob (the builder :o)). Shorter and more to the point. Thoughts? Open for suggestions.

**Comment by mischief** [comment] 2017-01-03 23:30
@edannenberg in keeping with silly names for container projects (kubernetes, docker, rkt), how about cooper? one who makes barrels, a kind of container

alternately something listed here https://en.wikipedia.org/wiki/Cooper_(profession)#.22Cooper.22_as_a_name

**Comment by soredake** [comment] 2017-01-07 17:29
Also it is very unclear how to start the initial assembly, with ./build.sh -s build fdsfgs I get 
```Error: image fdsfgs / bob not found 
failed to build fdsfgs / builder / bob```

**Comment by azimut** [comment] 2017-01-10 02:39
I would argue that would be better do nothing without any argument and show the help instead. Which should include some examples. I like the idea of finding my way through the tools I use.
-----
Other thing might be helpful (at least it would be to me now :p ) would be have a guide of "how to create new images" like, how to know which packages will go on the ROOT and which shouldn't. Might be is related to the DEPEND and RDEPEND. But I am not sure what workflow follow to just install the RDEPEND ones..
-----
btw, I am not crosscompiling now, just using arm as the stage3 with qemu and is working fine so far (except some things that fail like distcc and golang).

**Comment by UralZima** [comment] 2017-02-04 11:07
Hi everybody. Thanks for your active work, now it is more easy to understand. 
Some more questions:
1. I am trying to switch to GCC 5.4 in gentoobb as default compiler and more up-to-date toolchain. 
I have ~keyworded gcc in gentoobb/bob, added emerge gcc && gcc-config && source /etc/profile
After I need to update glibc, libtool and binutils. so I unmasked glibc in gentoobb/glibc, what about rest? where they exist?
I unmasked them all in bob and glibc, flaggie started to fail because of --strict, so I removed --strict. 

Also, there is gentoobb/gcc exist, but it is not used, when I build something like mariadb. Only glibc is used. For what purposes it needed? 

2. Is it ok to use bob for busybox, to not have/build 2 builders? What cons? 
3. I am going to add bash to all my containers, coz I often logging to them and busybox is not enough. So I change source from s6 to bash. Do I still need busybox? Does bash provide all utils like /bin/ls /bin/cat etc?
4. I offer to rename default namespace from gentoobb to bb. It is too long to write gentoobb when you use 'docker' app. I renamed for myself, but I think it is better by default. 
5. I am trying to build bind9 in container. it uses chroot by default, things came very complicated. Is there any easy way to do it?

Thank you very much for your awesome work!

**Comment by edannenberg** [comment] 2017-02-04 18:08
> I am trying to switch to GCC 5.4 in gentoobb as default compiler and more up-to-date toolchain.
I have ~keyworded gcc in gentoobb/bob, added emerge gcc && gcc-config && source /etc/profile
After I need to update glibc, libtool and binutils. so I unmasked glibc in gentoobb/glibc, what about rest? where they exist?
I unmasked them all in bob and glibc, flaggie started to fail because of --strict, so I removed --strict.

Not quite sure I understand, what is the exact problem? If you can push your changes to a fork I can take a quick look tomorrow.

> Also, there is gentoobb/gcc exist, but it is not used, when I build something like mariadb. Only glibc is 
used. For what purposes it needed?

I see, there seems to some confusion about the 2 phase build used by gentoo-bb. As a rule of thumb:

* Image names starting with `bob` are used in the first build phase and generally never leave the build host, this includes a complete stage3 with portage tree, etc. This is where all the compiling and heavy lifting takes places and where `build.sh` of each image is executed.
* Images that do not start with `bob` are final images and meant to be pushed to a registry. The only time those images are used during the build process is as image parent (`FROM` in Dockerfile) for other final images. 

So `gentoobb/gcc` is a final image, as MariaDB doesn't need gcc at runtime it has no need for it and can use the much smaller `gentoobb/glibc` image as parent instead. As an example where `gentoobb/gcc` is required check the `gentoobb/ruby-gcc` image. Some Ruby gem installs require native compiling, so you have to bite the bullet and include gcc in the final image.

> Is it ok to use bob for busybox, to not have/build 2 builders? What cons?

Totally up to you, glibc cons:

* slightly bigger image (around 2mb IIRC)
* dns resolution will not work when using a static glibc busybox binary, this a known bug/flaw in glibc with a patch, but AFAIK the patch never made it into official ebuild

> I am going to add bash to all my containers, coz I often logging to them and busybox is not enough. So I change source from s6 to bash.

Sure, again totally up to you, gentoo-bb does not make many assumptions about your final images.

> Do I still need busybox? Does bash provide all utils like /bin/ls /bin/cat etc?

Depends on your needs, just try and see what is missing. The reason for Busybox is that it provides much more then just a shell, but there are some subtile differences to the standard equivalents, like grep being somewhat limited, etc. Just play around and see what works best for you. :)

> I offer to rename default namespace from gentoobb to bb. It is too long to write gentoobb when you use 'docker' app. I renamed for myself, but I think it is better by default.

The project name will most likely change in the near future, will revisit then.

> I am trying to build bind9 in container. it uses chroot by default, things came very complicated. Is there any easy way to do it?

You can try building the bind package in the `configure_bob` hook first, this should take out all the friction from using a custom `ROOT` and give you a binary package. See #33 for details.

On a side note: ew, Bind. [TinyDNS](https://cr.yp.to/djbdns/tinydns.html) ftw. 😛

**Comment by edannenberg** [comment] 2017-02-04 18:23
> @edannenberg in keeping with silly names for container projects (kubernetes, docker, rkt), how about cooper? one who makes barrels, a kind of container
alternately something listed here https://en.wikipedia.org/wiki/Cooper_(profession)#.22Cooper.22_as_a_name

@mischief I like the meaning, but my mind always associates a freakin Mini-Cooper lol. `./cooper.sh build foo` is kinda neat though. Thinking about it a bit more the defining feature of gentoo-bb is nested builds, any obscure ideas for that? :)

**Comment by edannenberg** [comment] 2017-02-04 18:29
@azimut 

> I would argue that would be better do nothing without any argument and show the help instead. Which should include some examples. I like the idea of finding my way through the tools I use.

It's a valid point, currently experimenting a bit with [argbash](https://github.com/matejak/argbash), looks nice but not quite sure yet it can do what I have in mind.

> Other thing might be helpful (at least it would be to me now :p ) would be have a guide of "how to create new images" like, how to know which packages will go on the ROOT and which shouldn't. Might be is related to the DEPEND and RDEPEND. But I am not sure what workflow follow to just install the RDEPEND ones..

I'm actually not quite sure about DEPEND and RDEPEND myself at the moment, could potentially lead to some more savings in general. Some packages for example pull in bash even though they most likely don't really need it at runtime.

**Comment by azimut** [comment] 2017-02-05 05:48
@edannenberg I had in mind take the build.sh approach to be more similar to the approach you have with for example `docker`. When you type docker nothing happens, and you get a list of "actions" and flags. You then type `docker <ACTION>` and you get other help. Probably better described at the library these tools use https://github.com/spf13/cobra#concepts

Actually `emerge` takes care of just installing on ROOT the RDEPEND ones. So is not an issue for this project. Though it might be for the crosscompiling world.

**Comment by edannenberg** [comment] 2017-02-06 20:47
@azimut Exactly what I had in mind too, though I wasn't aware of cobra. Contextualized help certainly beats the old all in one `--help` approach. As for RDEPEND, I guess those kind of optimizations I mentioned earlier need to be done manually on a per package basis then.

**Comment by edannenberg** [comment] 2019-03-20 05:02
Please take a look at the new documentation, should cover all the mentioned issues new.

**Closed by edannenberg** 2019-03-20 05:02 UTC
Labels: question
